name: CI

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Create Classic Burning Crusade Package
      run: ./utils/packager/release.sh -g bcc
      env:
        CF_API_KEY: ${{ secrets.CF_API_TOKEN }}
        WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        WAGO_API_TOKEN: ${{ secrets.WAGO_API_KEY }}
        GITHUB_OAUTH: ${{ github.token }}
